pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

include ':app'
includeBuild("../..") {
    dependencySubstitution {
        substitute(module("co.optable:local-sdk")).using(project(":android_sdk"))
    }
}
rootProject.name = "DemoKotlin"